In [4]:
import yaml
import os
import pandas as pd
import numpy as np
from torch.utils.data import DataLoader
from nn_models import DefogDataset
with open('config.yml', 'r') as file:
    config = yaml.safe_load(file)
    

In [5]:
training_data = DefogDataset()

In [11]:
train_dataloader = DataLoader(training_data, batch_size=2, shuffle=True)

In [19]:
training_data[8]

(tensor([[-0.9166,  0.1274, -0.3449],
         [-0.9169,  0.1288, -0.3446],
         [-0.9188,  0.1315, -0.3455],
         ...,
         [-1.0074,  0.0821, -0.2463],
         [-1.0045,  0.0791, -0.2358],
         [-0.9972,  0.0767, -0.2351]], dtype=torch.float64),
 tensor([[0],
         [0],
         [0],
         ...,
         [0],
         [0],
         [0]]))

In [23]:
from torch import nn
import torch

In [34]:
rnn = nn.RNN(3, 2, 2)
input = torch.randn(20, 3)
h0 = torch.randn(2, 2)
output, hn = rnn(input, h0)

In [37]:
output.shape

torch.Size([20, 2])

In [41]:
assert output.shape == (20,3)

AssertionError: 

In [43]:
torch.sigmoid(output)

tensor([[0.2869, 0.4242],
        [0.3489, 0.4992],
        [0.2894, 0.5090],
        [0.4347, 0.6204],
        [0.3152, 0.6376],
        [0.3048, 0.5009],
        [0.3031, 0.5851],
        [0.3107, 0.6394],
        [0.3009, 0.4961],
        [0.3400, 0.4771],
        [0.3001, 0.4551],
        [0.2832, 0.4684],
        [0.2898, 0.5166],
        [0.2913, 0.4747],
        [0.3136, 0.5125],
        [0.2871, 0.4693],
        [0.3069, 0.5352],
        [0.3114, 0.6265],
        [0.3089, 0.5357],
        [0.3994, 0.6341]], grad_fn=<SigmoidBackward0>)

In [44]:
m = nn.Linear(2, 1)

In [45]:
m(output)

tensor([[-0.3514],
        [-0.0411],
        [-0.1817],
        [ 0.4036],
        [ 0.1411],
        [-0.1543],
        [ 0.0026],
        [ 0.1325],
        [-0.1742],
        [-0.1062],
        [-0.2547],
        [-0.2767],
        [-0.1661],
        [-0.2418],
        [-0.1085],
        [-0.2641],
        [-0.0833],
        [ 0.1079],
        [-0.0768],
        [ 0.3474]], grad_fn=<AddmmBackward0>)